# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_Seeed_vl53l0x')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_Seeed_vl53l0x')
    _Seeed_vl53l0x = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Seeed_vl53l0x', [dirname(__file__)])
        except ImportError:
            import _Seeed_vl53l0x
            return _Seeed_vl53l0x
        if fp is not None:
            try:
                _mod = imp.load_module('_Seeed_vl53l0x', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _Seeed_vl53l0x = swig_import_helper()
    del swig_import_helper
else:
    import _Seeed_vl53l0x
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

IIC_DEFAULT_ADDR = _Seeed_vl53l0x.IIC_DEFAULT_ADDR
CONTINUOUS_MODE_MESURE_TIME = _Seeed_vl53l0x.CONTINUOUS_MODE_MESURE_TIME
class Seeed_vl53l0x(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Seeed_vl53l0x, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Seeed_vl53l0x, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _Seeed_vl53l0x.delete_Seeed_vl53l0x
    __del__ = lambda self: None

    def print_pal_error(self, Status):
        return _Seeed_vl53l0x.Seeed_vl53l0x_print_pal_error(self, Status)

    def VL53L0X_common_init(self):
        return _Seeed_vl53l0x.Seeed_vl53l0x_VL53L0X_common_init(self)

    def VL53L0X_single_ranging_init(self):
        return _Seeed_vl53l0x.Seeed_vl53l0x_VL53L0X_single_ranging_init(self)

    def VL53L0X_high_speed_ranging_init(self):
        return _Seeed_vl53l0x.Seeed_vl53l0x_VL53L0X_high_speed_ranging_init(self)

    def VL53L0X_high_accuracy_ranging_init(self):
        return _Seeed_vl53l0x.Seeed_vl53l0x_VL53L0X_high_accuracy_ranging_init(self)

    def VL53L0X_long_distance_ranging_init(self):
        return _Seeed_vl53l0x.Seeed_vl53l0x_VL53L0X_long_distance_ranging_init(self)

    def VL53L0X_continuous_ranging_init(self):
        return _Seeed_vl53l0x.Seeed_vl53l0x_VL53L0X_continuous_ranging_init(self)

    def PerformSingleRangingMeasurement(self, RangingMeasurementData):
        return _Seeed_vl53l0x.Seeed_vl53l0x_PerformSingleRangingMeasurement(self, RangingMeasurementData)

    def PerformContinuousRangingMeasurement(self, RangingMeasurementData):
        return _Seeed_vl53l0x.Seeed_vl53l0x_PerformContinuousRangingMeasurement(self, RangingMeasurementData)

    def __init__(self):
        this = _Seeed_vl53l0x.new_Seeed_vl53l0x()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
Seeed_vl53l0x_swigregister = _Seeed_vl53l0x.Seeed_vl53l0x_swigregister
Seeed_vl53l0x_swigregister(Seeed_vl53l0x)

VL53L0X10_SPECIFICATION_VER_MAJOR = _Seeed_vl53l0x.VL53L0X10_SPECIFICATION_VER_MAJOR
VL53L0X10_SPECIFICATION_VER_MINOR = _Seeed_vl53l0x.VL53L0X10_SPECIFICATION_VER_MINOR
VL53L0X10_SPECIFICATION_VER_SUB = _Seeed_vl53l0x.VL53L0X10_SPECIFICATION_VER_SUB
VL53L0X10_SPECIFICATION_VER_REVISION = _Seeed_vl53l0x.VL53L0X10_SPECIFICATION_VER_REVISION
VL53L0X10_IMPLEMENTATION_VER_MAJOR = _Seeed_vl53l0x.VL53L0X10_IMPLEMENTATION_VER_MAJOR
VL53L0X10_IMPLEMENTATION_VER_MINOR = _Seeed_vl53l0x.VL53L0X10_IMPLEMENTATION_VER_MINOR
VL53L0X10_IMPLEMENTATION_VER_SUB = _Seeed_vl53l0x.VL53L0X10_IMPLEMENTATION_VER_SUB
VL53L0X10_IMPLEMENTATION_VER_REVISION = _Seeed_vl53l0x.VL53L0X10_IMPLEMENTATION_VER_REVISION
VL53L0X_SPECIFICATION_VER_MAJOR = _Seeed_vl53l0x.VL53L0X_SPECIFICATION_VER_MAJOR
VL53L0X_SPECIFICATION_VER_MINOR = _Seeed_vl53l0x.VL53L0X_SPECIFICATION_VER_MINOR
VL53L0X_SPECIFICATION_VER_SUB = _Seeed_vl53l0x.VL53L0X_SPECIFICATION_VER_SUB
VL53L0X_SPECIFICATION_VER_REVISION = _Seeed_vl53l0x.VL53L0X_SPECIFICATION_VER_REVISION
VL53L0X_IMPLEMENTATION_VER_MAJOR = _Seeed_vl53l0x.VL53L0X_IMPLEMENTATION_VER_MAJOR
VL53L0X_IMPLEMENTATION_VER_MINOR = _Seeed_vl53l0x.VL53L0X_IMPLEMENTATION_VER_MINOR
VL53L0X_IMPLEMENTATION_VER_SUB = _Seeed_vl53l0x.VL53L0X_IMPLEMENTATION_VER_SUB
VL53L0X_IMPLEMENTATION_VER_REVISION = _Seeed_vl53l0x.VL53L0X_IMPLEMENTATION_VER_REVISION
VL53L0X_DEFAULT_MAX_LOOP = _Seeed_vl53l0x.VL53L0X_DEFAULT_MAX_LOOP
VL53L0X_MAX_STRING_LENGTH = _Seeed_vl53l0x.VL53L0X_MAX_STRING_LENGTH
class VL53L0X_Version_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VL53L0X_Version_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VL53L0X_Version_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["revision"] = _Seeed_vl53l0x.VL53L0X_Version_t_revision_set
    __swig_getmethods__["revision"] = _Seeed_vl53l0x.VL53L0X_Version_t_revision_get
    if _newclass:
        revision = _swig_property(_Seeed_vl53l0x.VL53L0X_Version_t_revision_get, _Seeed_vl53l0x.VL53L0X_Version_t_revision_set)
    __swig_setmethods__["major"] = _Seeed_vl53l0x.VL53L0X_Version_t_major_set
    __swig_getmethods__["major"] = _Seeed_vl53l0x.VL53L0X_Version_t_major_get
    if _newclass:
        major = _swig_property(_Seeed_vl53l0x.VL53L0X_Version_t_major_get, _Seeed_vl53l0x.VL53L0X_Version_t_major_set)
    __swig_setmethods__["minor"] = _Seeed_vl53l0x.VL53L0X_Version_t_minor_set
    __swig_getmethods__["minor"] = _Seeed_vl53l0x.VL53L0X_Version_t_minor_get
    if _newclass:
        minor = _swig_property(_Seeed_vl53l0x.VL53L0X_Version_t_minor_get, _Seeed_vl53l0x.VL53L0X_Version_t_minor_set)
    __swig_setmethods__["build"] = _Seeed_vl53l0x.VL53L0X_Version_t_build_set
    __swig_getmethods__["build"] = _Seeed_vl53l0x.VL53L0X_Version_t_build_get
    if _newclass:
        build = _swig_property(_Seeed_vl53l0x.VL53L0X_Version_t_build_get, _Seeed_vl53l0x.VL53L0X_Version_t_build_set)

    def __init__(self):
        this = _Seeed_vl53l0x.new_VL53L0X_Version_t()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _Seeed_vl53l0x.delete_VL53L0X_Version_t
    __del__ = lambda self: None
VL53L0X_Version_t_swigregister = _Seeed_vl53l0x.VL53L0X_Version_t_swigregister
VL53L0X_Version_t_swigregister(VL53L0X_Version_t)

class VL53L0X_DeviceInfo_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VL53L0X_DeviceInfo_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VL53L0X_DeviceInfo_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["Name"] = _Seeed_vl53l0x.VL53L0X_DeviceInfo_t_Name_set
    __swig_getmethods__["Name"] = _Seeed_vl53l0x.VL53L0X_DeviceInfo_t_Name_get
    if _newclass:
        Name = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceInfo_t_Name_get, _Seeed_vl53l0x.VL53L0X_DeviceInfo_t_Name_set)
    __swig_setmethods__["Type"] = _Seeed_vl53l0x.VL53L0X_DeviceInfo_t_Type_set
    __swig_getmethods__["Type"] = _Seeed_vl53l0x.VL53L0X_DeviceInfo_t_Type_get
    if _newclass:
        Type = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceInfo_t_Type_get, _Seeed_vl53l0x.VL53L0X_DeviceInfo_t_Type_set)
    __swig_setmethods__["ProductId"] = _Seeed_vl53l0x.VL53L0X_DeviceInfo_t_ProductId_set
    __swig_getmethods__["ProductId"] = _Seeed_vl53l0x.VL53L0X_DeviceInfo_t_ProductId_get
    if _newclass:
        ProductId = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceInfo_t_ProductId_get, _Seeed_vl53l0x.VL53L0X_DeviceInfo_t_ProductId_set)
    __swig_setmethods__["ProductType"] = _Seeed_vl53l0x.VL53L0X_DeviceInfo_t_ProductType_set
    __swig_getmethods__["ProductType"] = _Seeed_vl53l0x.VL53L0X_DeviceInfo_t_ProductType_get
    if _newclass:
        ProductType = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceInfo_t_ProductType_get, _Seeed_vl53l0x.VL53L0X_DeviceInfo_t_ProductType_set)
    __swig_setmethods__["ProductRevisionMajor"] = _Seeed_vl53l0x.VL53L0X_DeviceInfo_t_ProductRevisionMajor_set
    __swig_getmethods__["ProductRevisionMajor"] = _Seeed_vl53l0x.VL53L0X_DeviceInfo_t_ProductRevisionMajor_get
    if _newclass:
        ProductRevisionMajor = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceInfo_t_ProductRevisionMajor_get, _Seeed_vl53l0x.VL53L0X_DeviceInfo_t_ProductRevisionMajor_set)
    __swig_setmethods__["ProductRevisionMinor"] = _Seeed_vl53l0x.VL53L0X_DeviceInfo_t_ProductRevisionMinor_set
    __swig_getmethods__["ProductRevisionMinor"] = _Seeed_vl53l0x.VL53L0X_DeviceInfo_t_ProductRevisionMinor_get
    if _newclass:
        ProductRevisionMinor = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceInfo_t_ProductRevisionMinor_get, _Seeed_vl53l0x.VL53L0X_DeviceInfo_t_ProductRevisionMinor_set)

    def __init__(self):
        this = _Seeed_vl53l0x.new_VL53L0X_DeviceInfo_t()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _Seeed_vl53l0x.delete_VL53L0X_DeviceInfo_t
    __del__ = lambda self: None
VL53L0X_DeviceInfo_t_swigregister = _Seeed_vl53l0x.VL53L0X_DeviceInfo_t_swigregister
VL53L0X_DeviceInfo_t_swigregister(VL53L0X_DeviceInfo_t)

class VL53L0X_DeviceParameters_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VL53L0X_DeviceParameters_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VL53L0X_DeviceParameters_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["DeviceMode"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_DeviceMode_set
    __swig_getmethods__["DeviceMode"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_DeviceMode_get
    if _newclass:
        DeviceMode = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceParameters_t_DeviceMode_get, _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_DeviceMode_set)
    __swig_setmethods__["HistogramMode"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_HistogramMode_set
    __swig_getmethods__["HistogramMode"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_HistogramMode_get
    if _newclass:
        HistogramMode = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceParameters_t_HistogramMode_get, _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_HistogramMode_set)
    __swig_setmethods__["MeasurementTimingBudgetMicroSeconds"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_MeasurementTimingBudgetMicroSeconds_set
    __swig_getmethods__["MeasurementTimingBudgetMicroSeconds"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_MeasurementTimingBudgetMicroSeconds_get
    if _newclass:
        MeasurementTimingBudgetMicroSeconds = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceParameters_t_MeasurementTimingBudgetMicroSeconds_get, _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_MeasurementTimingBudgetMicroSeconds_set)
    __swig_setmethods__["InterMeasurementPeriodMilliSeconds"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_InterMeasurementPeriodMilliSeconds_set
    __swig_getmethods__["InterMeasurementPeriodMilliSeconds"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_InterMeasurementPeriodMilliSeconds_get
    if _newclass:
        InterMeasurementPeriodMilliSeconds = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceParameters_t_InterMeasurementPeriodMilliSeconds_get, _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_InterMeasurementPeriodMilliSeconds_set)
    __swig_setmethods__["XTalkCompensationEnable"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_XTalkCompensationEnable_set
    __swig_getmethods__["XTalkCompensationEnable"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_XTalkCompensationEnable_get
    if _newclass:
        XTalkCompensationEnable = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceParameters_t_XTalkCompensationEnable_get, _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_XTalkCompensationEnable_set)
    __swig_setmethods__["XTalkCompensationRangeMilliMeter"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_XTalkCompensationRangeMilliMeter_set
    __swig_getmethods__["XTalkCompensationRangeMilliMeter"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_XTalkCompensationRangeMilliMeter_get
    if _newclass:
        XTalkCompensationRangeMilliMeter = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceParameters_t_XTalkCompensationRangeMilliMeter_get, _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_XTalkCompensationRangeMilliMeter_set)
    __swig_setmethods__["XTalkCompensationRateMegaCps"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_XTalkCompensationRateMegaCps_set
    __swig_getmethods__["XTalkCompensationRateMegaCps"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_XTalkCompensationRateMegaCps_get
    if _newclass:
        XTalkCompensationRateMegaCps = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceParameters_t_XTalkCompensationRateMegaCps_get, _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_XTalkCompensationRateMegaCps_set)
    __swig_setmethods__["RangeOffsetMicroMeters"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_RangeOffsetMicroMeters_set
    __swig_getmethods__["RangeOffsetMicroMeters"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_RangeOffsetMicroMeters_get
    if _newclass:
        RangeOffsetMicroMeters = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceParameters_t_RangeOffsetMicroMeters_get, _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_RangeOffsetMicroMeters_set)
    __swig_setmethods__["LimitChecksEnable"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_LimitChecksEnable_set
    __swig_getmethods__["LimitChecksEnable"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_LimitChecksEnable_get
    if _newclass:
        LimitChecksEnable = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceParameters_t_LimitChecksEnable_get, _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_LimitChecksEnable_set)
    __swig_setmethods__["LimitChecksStatus"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_LimitChecksStatus_set
    __swig_getmethods__["LimitChecksStatus"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_LimitChecksStatus_get
    if _newclass:
        LimitChecksStatus = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceParameters_t_LimitChecksStatus_get, _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_LimitChecksStatus_set)
    __swig_setmethods__["LimitChecksValue"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_LimitChecksValue_set
    __swig_getmethods__["LimitChecksValue"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_LimitChecksValue_get
    if _newclass:
        LimitChecksValue = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceParameters_t_LimitChecksValue_get, _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_LimitChecksValue_set)
    __swig_setmethods__["WrapAroundCheckEnable"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_WrapAroundCheckEnable_set
    __swig_getmethods__["WrapAroundCheckEnable"] = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_WrapAroundCheckEnable_get
    if _newclass:
        WrapAroundCheckEnable = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceParameters_t_WrapAroundCheckEnable_get, _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_WrapAroundCheckEnable_set)

    def __init__(self):
        this = _Seeed_vl53l0x.new_VL53L0X_DeviceParameters_t()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _Seeed_vl53l0x.delete_VL53L0X_DeviceParameters_t
    __del__ = lambda self: None
VL53L0X_DeviceParameters_t_swigregister = _Seeed_vl53l0x.VL53L0X_DeviceParameters_t_swigregister
VL53L0X_DeviceParameters_t_swigregister(VL53L0X_DeviceParameters_t)

class VL53L0X_DMaxData_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VL53L0X_DMaxData_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VL53L0X_DMaxData_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["AmbTuningWindowFactor_K"] = _Seeed_vl53l0x.VL53L0X_DMaxData_t_AmbTuningWindowFactor_K_set
    __swig_getmethods__["AmbTuningWindowFactor_K"] = _Seeed_vl53l0x.VL53L0X_DMaxData_t_AmbTuningWindowFactor_K_get
    if _newclass:
        AmbTuningWindowFactor_K = _swig_property(_Seeed_vl53l0x.VL53L0X_DMaxData_t_AmbTuningWindowFactor_K_get, _Seeed_vl53l0x.VL53L0X_DMaxData_t_AmbTuningWindowFactor_K_set)
    __swig_setmethods__["RetSignalAt0mm"] = _Seeed_vl53l0x.VL53L0X_DMaxData_t_RetSignalAt0mm_set
    __swig_getmethods__["RetSignalAt0mm"] = _Seeed_vl53l0x.VL53L0X_DMaxData_t_RetSignalAt0mm_get
    if _newclass:
        RetSignalAt0mm = _swig_property(_Seeed_vl53l0x.VL53L0X_DMaxData_t_RetSignalAt0mm_get, _Seeed_vl53l0x.VL53L0X_DMaxData_t_RetSignalAt0mm_set)

    def __init__(self):
        this = _Seeed_vl53l0x.new_VL53L0X_DMaxData_t()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _Seeed_vl53l0x.delete_VL53L0X_DMaxData_t
    __del__ = lambda self: None
VL53L0X_DMaxData_t_swigregister = _Seeed_vl53l0x.VL53L0X_DMaxData_t_swigregister
VL53L0X_DMaxData_t_swigregister(VL53L0X_DMaxData_t)

class VL53L0X_RangingMeasurementData_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VL53L0X_RangingMeasurementData_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VL53L0X_RangingMeasurementData_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["TimeStamp"] = _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_TimeStamp_set
    __swig_getmethods__["TimeStamp"] = _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_TimeStamp_get
    if _newclass:
        TimeStamp = _swig_property(_Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_TimeStamp_get, _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_TimeStamp_set)
    __swig_setmethods__["MeasurementTimeUsec"] = _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_MeasurementTimeUsec_set
    __swig_getmethods__["MeasurementTimeUsec"] = _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_MeasurementTimeUsec_get
    if _newclass:
        MeasurementTimeUsec = _swig_property(_Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_MeasurementTimeUsec_get, _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_MeasurementTimeUsec_set)
    __swig_setmethods__["RangeMilliMeter"] = _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_RangeMilliMeter_set
    __swig_getmethods__["RangeMilliMeter"] = _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_RangeMilliMeter_get
    if _newclass:
        RangeMilliMeter = _swig_property(_Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_RangeMilliMeter_get, _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_RangeMilliMeter_set)
    __swig_setmethods__["RangeDMaxMilliMeter"] = _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_RangeDMaxMilliMeter_set
    __swig_getmethods__["RangeDMaxMilliMeter"] = _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_RangeDMaxMilliMeter_get
    if _newclass:
        RangeDMaxMilliMeter = _swig_property(_Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_RangeDMaxMilliMeter_get, _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_RangeDMaxMilliMeter_set)
    __swig_setmethods__["SignalRateRtnMegaCps"] = _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_SignalRateRtnMegaCps_set
    __swig_getmethods__["SignalRateRtnMegaCps"] = _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_SignalRateRtnMegaCps_get
    if _newclass:
        SignalRateRtnMegaCps = _swig_property(_Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_SignalRateRtnMegaCps_get, _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_SignalRateRtnMegaCps_set)
    __swig_setmethods__["AmbientRateRtnMegaCps"] = _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_AmbientRateRtnMegaCps_set
    __swig_getmethods__["AmbientRateRtnMegaCps"] = _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_AmbientRateRtnMegaCps_get
    if _newclass:
        AmbientRateRtnMegaCps = _swig_property(_Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_AmbientRateRtnMegaCps_get, _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_AmbientRateRtnMegaCps_set)
    __swig_setmethods__["EffectiveSpadRtnCount"] = _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_EffectiveSpadRtnCount_set
    __swig_getmethods__["EffectiveSpadRtnCount"] = _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_EffectiveSpadRtnCount_get
    if _newclass:
        EffectiveSpadRtnCount = _swig_property(_Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_EffectiveSpadRtnCount_get, _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_EffectiveSpadRtnCount_set)
    __swig_setmethods__["ZoneId"] = _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_ZoneId_set
    __swig_getmethods__["ZoneId"] = _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_ZoneId_get
    if _newclass:
        ZoneId = _swig_property(_Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_ZoneId_get, _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_ZoneId_set)
    __swig_setmethods__["RangeFractionalPart"] = _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_RangeFractionalPart_set
    __swig_getmethods__["RangeFractionalPart"] = _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_RangeFractionalPart_get
    if _newclass:
        RangeFractionalPart = _swig_property(_Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_RangeFractionalPart_get, _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_RangeFractionalPart_set)
    __swig_setmethods__["RangeStatus"] = _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_RangeStatus_set
    __swig_getmethods__["RangeStatus"] = _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_RangeStatus_get
    if _newclass:
        RangeStatus = _swig_property(_Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_RangeStatus_get, _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_RangeStatus_set)

    def __init__(self):
        this = _Seeed_vl53l0x.new_VL53L0X_RangingMeasurementData_t()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _Seeed_vl53l0x.delete_VL53L0X_RangingMeasurementData_t
    __del__ = lambda self: None
VL53L0X_RangingMeasurementData_t_swigregister = _Seeed_vl53l0x.VL53L0X_RangingMeasurementData_t_swigregister
VL53L0X_RangingMeasurementData_t_swigregister(VL53L0X_RangingMeasurementData_t)

VL53L0X_HISTOGRAM_BUFFER_SIZE = _Seeed_vl53l0x.VL53L0X_HISTOGRAM_BUFFER_SIZE
class VL53L0X_HistogramMeasurementData_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VL53L0X_HistogramMeasurementData_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VL53L0X_HistogramMeasurementData_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["HistogramData"] = _Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_HistogramData_set
    __swig_getmethods__["HistogramData"] = _Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_HistogramData_get
    if _newclass:
        HistogramData = _swig_property(_Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_HistogramData_get, _Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_HistogramData_set)
    __swig_setmethods__["HistogramType"] = _Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_HistogramType_set
    __swig_getmethods__["HistogramType"] = _Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_HistogramType_get
    if _newclass:
        HistogramType = _swig_property(_Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_HistogramType_get, _Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_HistogramType_set)
    __swig_setmethods__["FirstBin"] = _Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_FirstBin_set
    __swig_getmethods__["FirstBin"] = _Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_FirstBin_get
    if _newclass:
        FirstBin = _swig_property(_Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_FirstBin_get, _Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_FirstBin_set)
    __swig_setmethods__["BufferSize"] = _Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_BufferSize_set
    __swig_getmethods__["BufferSize"] = _Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_BufferSize_get
    if _newclass:
        BufferSize = _swig_property(_Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_BufferSize_get, _Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_BufferSize_set)
    __swig_setmethods__["NumberOfBins"] = _Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_NumberOfBins_set
    __swig_getmethods__["NumberOfBins"] = _Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_NumberOfBins_get
    if _newclass:
        NumberOfBins = _swig_property(_Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_NumberOfBins_get, _Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_NumberOfBins_set)
    __swig_setmethods__["ErrorStatus"] = _Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_ErrorStatus_set
    __swig_getmethods__["ErrorStatus"] = _Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_ErrorStatus_get
    if _newclass:
        ErrorStatus = _swig_property(_Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_ErrorStatus_get, _Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_ErrorStatus_set)

    def __init__(self):
        this = _Seeed_vl53l0x.new_VL53L0X_HistogramMeasurementData_t()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _Seeed_vl53l0x.delete_VL53L0X_HistogramMeasurementData_t
    __del__ = lambda self: None
VL53L0X_HistogramMeasurementData_t_swigregister = _Seeed_vl53l0x.VL53L0X_HistogramMeasurementData_t_swigregister
VL53L0X_HistogramMeasurementData_t_swigregister(VL53L0X_HistogramMeasurementData_t)

VL53L0X_REF_SPAD_BUFFER_SIZE = _Seeed_vl53l0x.VL53L0X_REF_SPAD_BUFFER_SIZE
class VL53L0X_SpadData_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VL53L0X_SpadData_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VL53L0X_SpadData_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["RefSpadEnables"] = _Seeed_vl53l0x.VL53L0X_SpadData_t_RefSpadEnables_set
    __swig_getmethods__["RefSpadEnables"] = _Seeed_vl53l0x.VL53L0X_SpadData_t_RefSpadEnables_get
    if _newclass:
        RefSpadEnables = _swig_property(_Seeed_vl53l0x.VL53L0X_SpadData_t_RefSpadEnables_get, _Seeed_vl53l0x.VL53L0X_SpadData_t_RefSpadEnables_set)
    __swig_setmethods__["RefGoodSpadMap"] = _Seeed_vl53l0x.VL53L0X_SpadData_t_RefGoodSpadMap_set
    __swig_getmethods__["RefGoodSpadMap"] = _Seeed_vl53l0x.VL53L0X_SpadData_t_RefGoodSpadMap_get
    if _newclass:
        RefGoodSpadMap = _swig_property(_Seeed_vl53l0x.VL53L0X_SpadData_t_RefGoodSpadMap_get, _Seeed_vl53l0x.VL53L0X_SpadData_t_RefGoodSpadMap_set)

    def __init__(self):
        this = _Seeed_vl53l0x.new_VL53L0X_SpadData_t()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _Seeed_vl53l0x.delete_VL53L0X_SpadData_t
    __del__ = lambda self: None
VL53L0X_SpadData_t_swigregister = _Seeed_vl53l0x.VL53L0X_SpadData_t_swigregister
VL53L0X_SpadData_t_swigregister(VL53L0X_SpadData_t)

class VL53L0X_DeviceSpecificParameters_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VL53L0X_DeviceSpecificParameters_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VL53L0X_DeviceSpecificParameters_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["OscFrequencyMHz"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_OscFrequencyMHz_set
    __swig_getmethods__["OscFrequencyMHz"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_OscFrequencyMHz_get
    if _newclass:
        OscFrequencyMHz = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_OscFrequencyMHz_get, _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_OscFrequencyMHz_set)
    __swig_setmethods__["LastEncodedTimeout"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_LastEncodedTimeout_set
    __swig_getmethods__["LastEncodedTimeout"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_LastEncodedTimeout_get
    if _newclass:
        LastEncodedTimeout = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_LastEncodedTimeout_get, _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_LastEncodedTimeout_set)
    __swig_setmethods__["Pin0GpioFunctionality"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_Pin0GpioFunctionality_set
    __swig_getmethods__["Pin0GpioFunctionality"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_Pin0GpioFunctionality_get
    if _newclass:
        Pin0GpioFunctionality = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_Pin0GpioFunctionality_get, _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_Pin0GpioFunctionality_set)
    __swig_setmethods__["FinalRangeTimeoutMicroSecs"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_FinalRangeTimeoutMicroSecs_set
    __swig_getmethods__["FinalRangeTimeoutMicroSecs"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_FinalRangeTimeoutMicroSecs_get
    if _newclass:
        FinalRangeTimeoutMicroSecs = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_FinalRangeTimeoutMicroSecs_get, _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_FinalRangeTimeoutMicroSecs_set)
    __swig_setmethods__["FinalRangeVcselPulsePeriod"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_FinalRangeVcselPulsePeriod_set
    __swig_getmethods__["FinalRangeVcselPulsePeriod"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_FinalRangeVcselPulsePeriod_get
    if _newclass:
        FinalRangeVcselPulsePeriod = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_FinalRangeVcselPulsePeriod_get, _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_FinalRangeVcselPulsePeriod_set)
    __swig_setmethods__["PreRangeTimeoutMicroSecs"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_PreRangeTimeoutMicroSecs_set
    __swig_getmethods__["PreRangeTimeoutMicroSecs"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_PreRangeTimeoutMicroSecs_get
    if _newclass:
        PreRangeTimeoutMicroSecs = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_PreRangeTimeoutMicroSecs_get, _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_PreRangeTimeoutMicroSecs_set)
    __swig_setmethods__["PreRangeVcselPulsePeriod"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_PreRangeVcselPulsePeriod_set
    __swig_getmethods__["PreRangeVcselPulsePeriod"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_PreRangeVcselPulsePeriod_get
    if _newclass:
        PreRangeVcselPulsePeriod = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_PreRangeVcselPulsePeriod_get, _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_PreRangeVcselPulsePeriod_set)
    __swig_setmethods__["SigmaEstRefArray"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_SigmaEstRefArray_set
    __swig_getmethods__["SigmaEstRefArray"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_SigmaEstRefArray_get
    if _newclass:
        SigmaEstRefArray = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_SigmaEstRefArray_get, _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_SigmaEstRefArray_set)
    __swig_setmethods__["SigmaEstEffPulseWidth"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_SigmaEstEffPulseWidth_set
    __swig_getmethods__["SigmaEstEffPulseWidth"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_SigmaEstEffPulseWidth_get
    if _newclass:
        SigmaEstEffPulseWidth = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_SigmaEstEffPulseWidth_get, _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_SigmaEstEffPulseWidth_set)
    __swig_setmethods__["SigmaEstEffAmbWidth"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_SigmaEstEffAmbWidth_set
    __swig_getmethods__["SigmaEstEffAmbWidth"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_SigmaEstEffAmbWidth_get
    if _newclass:
        SigmaEstEffAmbWidth = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_SigmaEstEffAmbWidth_get, _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_SigmaEstEffAmbWidth_set)
    __swig_setmethods__["ReadDataFromDeviceDone"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_ReadDataFromDeviceDone_set
    __swig_getmethods__["ReadDataFromDeviceDone"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_ReadDataFromDeviceDone_get
    if _newclass:
        ReadDataFromDeviceDone = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_ReadDataFromDeviceDone_get, _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_ReadDataFromDeviceDone_set)
    __swig_setmethods__["ModuleId"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_ModuleId_set
    __swig_getmethods__["ModuleId"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_ModuleId_get
    if _newclass:
        ModuleId = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_ModuleId_get, _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_ModuleId_set)
    __swig_setmethods__["Revision"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_Revision_set
    __swig_getmethods__["Revision"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_Revision_get
    if _newclass:
        Revision = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_Revision_get, _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_Revision_set)
    __swig_setmethods__["ProductId"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_ProductId_set
    __swig_getmethods__["ProductId"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_ProductId_get
    if _newclass:
        ProductId = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_ProductId_get, _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_ProductId_set)
    __swig_setmethods__["ReferenceSpadCount"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_ReferenceSpadCount_set
    __swig_getmethods__["ReferenceSpadCount"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_ReferenceSpadCount_get
    if _newclass:
        ReferenceSpadCount = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_ReferenceSpadCount_get, _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_ReferenceSpadCount_set)
    __swig_setmethods__["ReferenceSpadType"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_ReferenceSpadType_set
    __swig_getmethods__["ReferenceSpadType"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_ReferenceSpadType_get
    if _newclass:
        ReferenceSpadType = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_ReferenceSpadType_get, _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_ReferenceSpadType_set)
    __swig_setmethods__["RefSpadsInitialised"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_RefSpadsInitialised_set
    __swig_getmethods__["RefSpadsInitialised"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_RefSpadsInitialised_get
    if _newclass:
        RefSpadsInitialised = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_RefSpadsInitialised_get, _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_RefSpadsInitialised_set)
    __swig_setmethods__["PartUIDUpper"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_PartUIDUpper_set
    __swig_getmethods__["PartUIDUpper"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_PartUIDUpper_get
    if _newclass:
        PartUIDUpper = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_PartUIDUpper_get, _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_PartUIDUpper_set)
    __swig_setmethods__["PartUIDLower"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_PartUIDLower_set
    __swig_getmethods__["PartUIDLower"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_PartUIDLower_get
    if _newclass:
        PartUIDLower = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_PartUIDLower_get, _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_PartUIDLower_set)
    __swig_setmethods__["SignalRateMeasFixed400mm"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_SignalRateMeasFixed400mm_set
    __swig_getmethods__["SignalRateMeasFixed400mm"] = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_SignalRateMeasFixed400mm_get
    if _newclass:
        SignalRateMeasFixed400mm = _swig_property(_Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_SignalRateMeasFixed400mm_get, _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_SignalRateMeasFixed400mm_set)

    def __init__(self):
        this = _Seeed_vl53l0x.new_VL53L0X_DeviceSpecificParameters_t()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _Seeed_vl53l0x.delete_VL53L0X_DeviceSpecificParameters_t
    __del__ = lambda self: None
VL53L0X_DeviceSpecificParameters_t_swigregister = _Seeed_vl53l0x.VL53L0X_DeviceSpecificParameters_t_swigregister
VL53L0X_DeviceSpecificParameters_t_swigregister(VL53L0X_DeviceSpecificParameters_t)

class VL53L0X_DevData_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VL53L0X_DevData_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VL53L0X_DevData_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["DMaxData"] = _Seeed_vl53l0x.VL53L0X_DevData_t_DMaxData_set
    __swig_getmethods__["DMaxData"] = _Seeed_vl53l0x.VL53L0X_DevData_t_DMaxData_get
    if _newclass:
        DMaxData = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_DMaxData_get, _Seeed_vl53l0x.VL53L0X_DevData_t_DMaxData_set)
    __swig_setmethods__["Part2PartOffsetNVMMicroMeter"] = _Seeed_vl53l0x.VL53L0X_DevData_t_Part2PartOffsetNVMMicroMeter_set
    __swig_getmethods__["Part2PartOffsetNVMMicroMeter"] = _Seeed_vl53l0x.VL53L0X_DevData_t_Part2PartOffsetNVMMicroMeter_get
    if _newclass:
        Part2PartOffsetNVMMicroMeter = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_Part2PartOffsetNVMMicroMeter_get, _Seeed_vl53l0x.VL53L0X_DevData_t_Part2PartOffsetNVMMicroMeter_set)
    __swig_setmethods__["Part2PartOffsetAdjustmentNVMMicroMeter"] = _Seeed_vl53l0x.VL53L0X_DevData_t_Part2PartOffsetAdjustmentNVMMicroMeter_set
    __swig_getmethods__["Part2PartOffsetAdjustmentNVMMicroMeter"] = _Seeed_vl53l0x.VL53L0X_DevData_t_Part2PartOffsetAdjustmentNVMMicroMeter_get
    if _newclass:
        Part2PartOffsetAdjustmentNVMMicroMeter = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_Part2PartOffsetAdjustmentNVMMicroMeter_get, _Seeed_vl53l0x.VL53L0X_DevData_t_Part2PartOffsetAdjustmentNVMMicroMeter_set)
    __swig_setmethods__["CurrentParameters"] = _Seeed_vl53l0x.VL53L0X_DevData_t_CurrentParameters_set
    __swig_getmethods__["CurrentParameters"] = _Seeed_vl53l0x.VL53L0X_DevData_t_CurrentParameters_get
    if _newclass:
        CurrentParameters = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_CurrentParameters_get, _Seeed_vl53l0x.VL53L0X_DevData_t_CurrentParameters_set)
    __swig_setmethods__["LastRangeMeasure"] = _Seeed_vl53l0x.VL53L0X_DevData_t_LastRangeMeasure_set
    __swig_getmethods__["LastRangeMeasure"] = _Seeed_vl53l0x.VL53L0X_DevData_t_LastRangeMeasure_get
    if _newclass:
        LastRangeMeasure = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_LastRangeMeasure_get, _Seeed_vl53l0x.VL53L0X_DevData_t_LastRangeMeasure_set)
    __swig_setmethods__["LastHistogramMeasure"] = _Seeed_vl53l0x.VL53L0X_DevData_t_LastHistogramMeasure_set
    __swig_getmethods__["LastHistogramMeasure"] = _Seeed_vl53l0x.VL53L0X_DevData_t_LastHistogramMeasure_get
    if _newclass:
        LastHistogramMeasure = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_LastHistogramMeasure_get, _Seeed_vl53l0x.VL53L0X_DevData_t_LastHistogramMeasure_set)
    __swig_setmethods__["DeviceSpecificParameters"] = _Seeed_vl53l0x.VL53L0X_DevData_t_DeviceSpecificParameters_set
    __swig_getmethods__["DeviceSpecificParameters"] = _Seeed_vl53l0x.VL53L0X_DevData_t_DeviceSpecificParameters_get
    if _newclass:
        DeviceSpecificParameters = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_DeviceSpecificParameters_get, _Seeed_vl53l0x.VL53L0X_DevData_t_DeviceSpecificParameters_set)
    __swig_setmethods__["SpadData"] = _Seeed_vl53l0x.VL53L0X_DevData_t_SpadData_set
    __swig_getmethods__["SpadData"] = _Seeed_vl53l0x.VL53L0X_DevData_t_SpadData_get
    if _newclass:
        SpadData = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_SpadData_get, _Seeed_vl53l0x.VL53L0X_DevData_t_SpadData_set)
    __swig_setmethods__["SequenceConfig"] = _Seeed_vl53l0x.VL53L0X_DevData_t_SequenceConfig_set
    __swig_getmethods__["SequenceConfig"] = _Seeed_vl53l0x.VL53L0X_DevData_t_SequenceConfig_get
    if _newclass:
        SequenceConfig = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_SequenceConfig_get, _Seeed_vl53l0x.VL53L0X_DevData_t_SequenceConfig_set)
    __swig_setmethods__["RangeFractionalEnable"] = _Seeed_vl53l0x.VL53L0X_DevData_t_RangeFractionalEnable_set
    __swig_getmethods__["RangeFractionalEnable"] = _Seeed_vl53l0x.VL53L0X_DevData_t_RangeFractionalEnable_get
    if _newclass:
        RangeFractionalEnable = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_RangeFractionalEnable_get, _Seeed_vl53l0x.VL53L0X_DevData_t_RangeFractionalEnable_set)
    __swig_setmethods__["PalState"] = _Seeed_vl53l0x.VL53L0X_DevData_t_PalState_set
    __swig_getmethods__["PalState"] = _Seeed_vl53l0x.VL53L0X_DevData_t_PalState_get
    if _newclass:
        PalState = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_PalState_get, _Seeed_vl53l0x.VL53L0X_DevData_t_PalState_set)
    __swig_setmethods__["PowerMode"] = _Seeed_vl53l0x.VL53L0X_DevData_t_PowerMode_set
    __swig_getmethods__["PowerMode"] = _Seeed_vl53l0x.VL53L0X_DevData_t_PowerMode_get
    if _newclass:
        PowerMode = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_PowerMode_get, _Seeed_vl53l0x.VL53L0X_DevData_t_PowerMode_set)
    __swig_setmethods__["SigmaEstRefArray"] = _Seeed_vl53l0x.VL53L0X_DevData_t_SigmaEstRefArray_set
    __swig_getmethods__["SigmaEstRefArray"] = _Seeed_vl53l0x.VL53L0X_DevData_t_SigmaEstRefArray_get
    if _newclass:
        SigmaEstRefArray = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_SigmaEstRefArray_get, _Seeed_vl53l0x.VL53L0X_DevData_t_SigmaEstRefArray_set)
    __swig_setmethods__["SigmaEstEffPulseWidth"] = _Seeed_vl53l0x.VL53L0X_DevData_t_SigmaEstEffPulseWidth_set
    __swig_getmethods__["SigmaEstEffPulseWidth"] = _Seeed_vl53l0x.VL53L0X_DevData_t_SigmaEstEffPulseWidth_get
    if _newclass:
        SigmaEstEffPulseWidth = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_SigmaEstEffPulseWidth_get, _Seeed_vl53l0x.VL53L0X_DevData_t_SigmaEstEffPulseWidth_set)
    __swig_setmethods__["SigmaEstEffAmbWidth"] = _Seeed_vl53l0x.VL53L0X_DevData_t_SigmaEstEffAmbWidth_set
    __swig_getmethods__["SigmaEstEffAmbWidth"] = _Seeed_vl53l0x.VL53L0X_DevData_t_SigmaEstEffAmbWidth_get
    if _newclass:
        SigmaEstEffAmbWidth = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_SigmaEstEffAmbWidth_get, _Seeed_vl53l0x.VL53L0X_DevData_t_SigmaEstEffAmbWidth_set)
    __swig_setmethods__["StopVariable"] = _Seeed_vl53l0x.VL53L0X_DevData_t_StopVariable_set
    __swig_getmethods__["StopVariable"] = _Seeed_vl53l0x.VL53L0X_DevData_t_StopVariable_get
    if _newclass:
        StopVariable = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_StopVariable_get, _Seeed_vl53l0x.VL53L0X_DevData_t_StopVariable_set)
    __swig_setmethods__["targetRefRate"] = _Seeed_vl53l0x.VL53L0X_DevData_t_targetRefRate_set
    __swig_getmethods__["targetRefRate"] = _Seeed_vl53l0x.VL53L0X_DevData_t_targetRefRate_get
    if _newclass:
        targetRefRate = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_targetRefRate_get, _Seeed_vl53l0x.VL53L0X_DevData_t_targetRefRate_set)
    __swig_setmethods__["SigmaEstimate"] = _Seeed_vl53l0x.VL53L0X_DevData_t_SigmaEstimate_set
    __swig_getmethods__["SigmaEstimate"] = _Seeed_vl53l0x.VL53L0X_DevData_t_SigmaEstimate_get
    if _newclass:
        SigmaEstimate = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_SigmaEstimate_get, _Seeed_vl53l0x.VL53L0X_DevData_t_SigmaEstimate_set)
    __swig_setmethods__["SignalEstimate"] = _Seeed_vl53l0x.VL53L0X_DevData_t_SignalEstimate_set
    __swig_getmethods__["SignalEstimate"] = _Seeed_vl53l0x.VL53L0X_DevData_t_SignalEstimate_get
    if _newclass:
        SignalEstimate = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_SignalEstimate_get, _Seeed_vl53l0x.VL53L0X_DevData_t_SignalEstimate_set)
    __swig_setmethods__["LastSignalRefMcps"] = _Seeed_vl53l0x.VL53L0X_DevData_t_LastSignalRefMcps_set
    __swig_getmethods__["LastSignalRefMcps"] = _Seeed_vl53l0x.VL53L0X_DevData_t_LastSignalRefMcps_get
    if _newclass:
        LastSignalRefMcps = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_LastSignalRefMcps_get, _Seeed_vl53l0x.VL53L0X_DevData_t_LastSignalRefMcps_set)
    __swig_setmethods__["pTuningSettingsPointer"] = _Seeed_vl53l0x.VL53L0X_DevData_t_pTuningSettingsPointer_set
    __swig_getmethods__["pTuningSettingsPointer"] = _Seeed_vl53l0x.VL53L0X_DevData_t_pTuningSettingsPointer_get
    if _newclass:
        pTuningSettingsPointer = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_pTuningSettingsPointer_get, _Seeed_vl53l0x.VL53L0X_DevData_t_pTuningSettingsPointer_set)
    __swig_setmethods__["UseInternalTuningSettings"] = _Seeed_vl53l0x.VL53L0X_DevData_t_UseInternalTuningSettings_set
    __swig_getmethods__["UseInternalTuningSettings"] = _Seeed_vl53l0x.VL53L0X_DevData_t_UseInternalTuningSettings_get
    if _newclass:
        UseInternalTuningSettings = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_UseInternalTuningSettings_get, _Seeed_vl53l0x.VL53L0X_DevData_t_UseInternalTuningSettings_set)
    __swig_setmethods__["LinearityCorrectiveGain"] = _Seeed_vl53l0x.VL53L0X_DevData_t_LinearityCorrectiveGain_set
    __swig_getmethods__["LinearityCorrectiveGain"] = _Seeed_vl53l0x.VL53L0X_DevData_t_LinearityCorrectiveGain_get
    if _newclass:
        LinearityCorrectiveGain = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_LinearityCorrectiveGain_get, _Seeed_vl53l0x.VL53L0X_DevData_t_LinearityCorrectiveGain_set)
    __swig_setmethods__["DmaxCalRangeMilliMeter"] = _Seeed_vl53l0x.VL53L0X_DevData_t_DmaxCalRangeMilliMeter_set
    __swig_getmethods__["DmaxCalRangeMilliMeter"] = _Seeed_vl53l0x.VL53L0X_DevData_t_DmaxCalRangeMilliMeter_get
    if _newclass:
        DmaxCalRangeMilliMeter = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_DmaxCalRangeMilliMeter_get, _Seeed_vl53l0x.VL53L0X_DevData_t_DmaxCalRangeMilliMeter_set)
    __swig_setmethods__["DmaxCalSignalRateRtnMegaCps"] = _Seeed_vl53l0x.VL53L0X_DevData_t_DmaxCalSignalRateRtnMegaCps_set
    __swig_getmethods__["DmaxCalSignalRateRtnMegaCps"] = _Seeed_vl53l0x.VL53L0X_DevData_t_DmaxCalSignalRateRtnMegaCps_get
    if _newclass:
        DmaxCalSignalRateRtnMegaCps = _swig_property(_Seeed_vl53l0x.VL53L0X_DevData_t_DmaxCalSignalRateRtnMegaCps_get, _Seeed_vl53l0x.VL53L0X_DevData_t_DmaxCalSignalRateRtnMegaCps_set)

    def __init__(self):
        this = _Seeed_vl53l0x.new_VL53L0X_DevData_t()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _Seeed_vl53l0x.delete_VL53L0X_DevData_t
    __del__ = lambda self: None
VL53L0X_DevData_t_swigregister = _Seeed_vl53l0x.VL53L0X_DevData_t_swigregister
VL53L0X_DevData_t_swigregister(VL53L0X_DevData_t)

class VL53L0X_SchedulerSequenceSteps_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VL53L0X_SchedulerSequenceSteps_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VL53L0X_SchedulerSequenceSteps_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["TccOn"] = _Seeed_vl53l0x.VL53L0X_SchedulerSequenceSteps_t_TccOn_set
    __swig_getmethods__["TccOn"] = _Seeed_vl53l0x.VL53L0X_SchedulerSequenceSteps_t_TccOn_get
    if _newclass:
        TccOn = _swig_property(_Seeed_vl53l0x.VL53L0X_SchedulerSequenceSteps_t_TccOn_get, _Seeed_vl53l0x.VL53L0X_SchedulerSequenceSteps_t_TccOn_set)
    __swig_setmethods__["MsrcOn"] = _Seeed_vl53l0x.VL53L0X_SchedulerSequenceSteps_t_MsrcOn_set
    __swig_getmethods__["MsrcOn"] = _Seeed_vl53l0x.VL53L0X_SchedulerSequenceSteps_t_MsrcOn_get
    if _newclass:
        MsrcOn = _swig_property(_Seeed_vl53l0x.VL53L0X_SchedulerSequenceSteps_t_MsrcOn_get, _Seeed_vl53l0x.VL53L0X_SchedulerSequenceSteps_t_MsrcOn_set)
    __swig_setmethods__["DssOn"] = _Seeed_vl53l0x.VL53L0X_SchedulerSequenceSteps_t_DssOn_set
    __swig_getmethods__["DssOn"] = _Seeed_vl53l0x.VL53L0X_SchedulerSequenceSteps_t_DssOn_get
    if _newclass:
        DssOn = _swig_property(_Seeed_vl53l0x.VL53L0X_SchedulerSequenceSteps_t_DssOn_get, _Seeed_vl53l0x.VL53L0X_SchedulerSequenceSteps_t_DssOn_set)
    __swig_setmethods__["PreRangeOn"] = _Seeed_vl53l0x.VL53L0X_SchedulerSequenceSteps_t_PreRangeOn_set
    __swig_getmethods__["PreRangeOn"] = _Seeed_vl53l0x.VL53L0X_SchedulerSequenceSteps_t_PreRangeOn_get
    if _newclass:
        PreRangeOn = _swig_property(_Seeed_vl53l0x.VL53L0X_SchedulerSequenceSteps_t_PreRangeOn_get, _Seeed_vl53l0x.VL53L0X_SchedulerSequenceSteps_t_PreRangeOn_set)
    __swig_setmethods__["FinalRangeOn"] = _Seeed_vl53l0x.VL53L0X_SchedulerSequenceSteps_t_FinalRangeOn_set
    __swig_getmethods__["FinalRangeOn"] = _Seeed_vl53l0x.VL53L0X_SchedulerSequenceSteps_t_FinalRangeOn_get
    if _newclass:
        FinalRangeOn = _swig_property(_Seeed_vl53l0x.VL53L0X_SchedulerSequenceSteps_t_FinalRangeOn_get, _Seeed_vl53l0x.VL53L0X_SchedulerSequenceSteps_t_FinalRangeOn_set)

    def __init__(self):
        this = _Seeed_vl53l0x.new_VL53L0X_SchedulerSequenceSteps_t()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _Seeed_vl53l0x.delete_VL53L0X_SchedulerSequenceSteps_t
    __del__ = lambda self: None
VL53L0X_SchedulerSequenceSteps_t_swigregister = _Seeed_vl53l0x.VL53L0X_SchedulerSequenceSteps_t_swigregister
VL53L0X_SchedulerSequenceSteps_t_swigregister(VL53L0X_SchedulerSequenceSteps_t)

VL53L0X_SEQUENCESTEP_NUMBER_OF_CHECKS = _Seeed_vl53l0x.VL53L0X_SEQUENCESTEP_NUMBER_OF_CHECKS
# This file is compatible with both classic and new-style classes.


